### ISSUE TITLE
Option to Preserve Consumption Records When Adjusting Budget

### ISSUE THREAD

**Issue by Cyuel** [danilkinkin/buckwheat#108]
**Issue body:**
**Background and Description:**
Users currently do not have the option to maintain their existing consumption records when modifying their budget settings. This feature would greatly benefit users who receive additional funds during a budget cycle and wish to incorporate them without resetting their consumption history. 

**Feature Requirement:**
It is requested to implement a feature that allows users to choose whether to retain their current consumption records when adjusting their budget. For instance, if a user has allocated a $100 budget over 7 days and receives an extra $20 on day 3, they should be able to add this amount to the existing budget, recalculate the remaining balance, and continue with the original consumption records for the cycle.

Your consideration of this feature implementation would be highly appreciated. Thank you for your attention to this request.

**Comment by danilkinkin** [comment]
It's now available in release [v4.7.0](https://github.com/danilkinkin/buckwheat/releases/tag/4.7.0)

**Comment by ReRokutosei** [comment]
Thanks🙏
