### ISSUE TITLE
crash when opening transaction history after editing an entry.

### ISSUE THREAD

**Issue by brunobmgit** [danilkinkin/buckwheat#112]
**Describe the bug**
The app crashes when I try to edit the dates on more than one transaction in sequence.

**To Reproduce**
1. Have a transaction registered with todays date.
2. Slide down to open the transaction history.
3. Slide right to edit a transaction from today and change its date to some day other than the current day, and save changes taping on the checkmark.
4. Slide down to open history again.
While sliding down, the app crashes.

**Expected behavior**
The app should open history and show the edited transaction with the updated date without crashing.

**Please complete the following information:**
 - Device: Xiaomi mi 9T
 - OS: Android 14
 - Version 4.5.5

**Comment by danilkinkin** [comment]
Thanks for the info, and sorry for long answer. Yep, it's confirmed, fixed and will be published in next release

**Comment by danilkinkin** [comment]
Fixed in version [4.7.0](https://github.com/danilkinkin/buckwheat/releases/tag/4.7.0). If problem still exist, please reopen topic
