### ISSUE TITLE
Add an additional account

### ISSUE THREAD

**Issue by franco27** [danilkinkin/buckwheat#116]
Hello,

I see that it is not possible to add an additional account.
Currently, your application is limited to one account.
The ability to assign a color to an account.
For example:
Account A in blue.
Account B in green.
With the ability to easily switch between accounts.

I have two bank accounts.

I just discovered your application and I really find it excellent. Congratulations for its original functioning.

Thank you

**Comment by danilkinkin** [comment]
Hello, I think is same [issue](https://github.com/danilkinkin/buckwheat/issues/34)
