### ISSUE TITLE
Typo in rus translate

### ISSUE THREAD

**Issue by SergeyProL** [danilkinkin/buckwheat#14]
На самом видном месте)
![Screenshot_2022-11-20-10-12-51-469-edit_com danilkinkin buckwheat](https://user-images.githubusercontent.com/6121086/202890459-78a2836d-7080-4a21-a8e4-6dd920dd4f2b.jpg)

**Comment by danilkinkin** [comment]
Resolved in version [1.0-beta4](https://github.com/danilkinkin/buckwheat/releases/tag/1.0-beta4)
