### ISSUE TITLE
Crash after installation

### ISSUE THREAD

**Issue by alpha4041** [danilkinkin/buckwheat#15]
After installing the application for the first time, I can't open it because it crashes.

Logcat url: https://bin.kv2.dev/~6379e400e599576ea02b1f2c

**Comment by uli-on** [comment]
Repeated auto-closing of Buckwheat also on Android 10. I'm presented with a flash of what seems a PIN keyboard and the introductory screen that's superseded with the modal dialogue reporting Buckwheat's repeated quitting. (No log file, sorry)

**Comment by uli-on** [comment]
BTW, I'm behind a firewall and I just saw Buckwheat tried to connect to googleusercontent.com. Is that necessary? Is it causing the crash?

**Comment by alpha4041** [comment]
> BTW, I'm behind a firewall and I just saw Buckwheat tried to connect to googleusercontent.com. Is that necessary? (12io.sentry?) Is it causing the crash?

I also have a flash of the introductory screen, I don't use a firewall so I don't think that is the cause.

**Comment by danilkinkin** [comment]
> BTW, I'm behind a firewall and I just saw Buckwheat tried to connect to googleusercontent.com. Is that necessary? (12io.sentry?) Is it causing the crash?

I'm not sure what the googleusercontent.com address is, but the app uses sentry to send error stack traces. I will study what kind of address this may be and I think it is worth adding the option to disable sending errors, it will be more correct. Created issue #18

**Comment by danilkinkin** [comment]
About the problem, I see why it might be and will try to reproduce the problem later. Added a task to the [board](https://github.com/users/danilkinkin/projects/2/views/1), you can follow the progress

**Comment by danilkinkin** [comment]
Fixed in version [1.1](https://github.com/danilkinkin/buckwheat/releases/tag/1.1)
