### ISSUE TITLE
Add option to disable sending sentry errors

### ISSUE THREAD

**Issue by danilkinkin** [danilkinkin/buckwheat#18]
You need to give the user a choice whether to send crash reports. That will be more correct

**Comment by uli-on** [comment]
> I will study what kind of address this may be

The IP address Buckwheat tries to connect to is 34.120.195.249 on port 443.

**Comment by danilkinkin** [comment]
Implemented in version [1.1](https://github.com/danilkinkin/buckwheat/releases/tag/1.1)
