### ISSUE TITLE
Edit already added spent

### ISSUE THREAD

**Issue by adharshgec** [danilkinkin/buckwheat#24]
**Is your feature request related to a problem? Please describe.**
An already added spent cannot be edited/deleted. I think it should be a core feature. Apart from that it's a beautiful and intuitive app!

**Describe the solution you'd like**
An edit option in the list of today's spents, so that we can edit/delete a previous spent.

**Describe alternatives you've considered**
No other alternative I can think of.

**Additional context**
None

**Comment by danilkinkin** [comment]
Thank you for the message. Yes, perhaps it should have been on start in the application. I'll take it in development in the coming days

**Comment by danilkinkin** [comment]
Implemented in version [1.4](https://github.com/danilkinkin/buckwheat/releases/tag/1.4)

**Comment by hjek** [comment]
it is possible to edit an entry?

i'm trying this app out and accidentally added a transaction twice. now i can't find a way to remove it.

in the **history** view nothing happens when pressing a transaction. i can't figure out how to access this functionality.
