### ISSUE TITLE
Cursor not moving with finger in textbox

### ISSUE THREAD

**Issue by danilkinkin** [danilkinkin/buckwheat#3]

**Comment by jedi1150** [comment]
This issue was resolved in compose 1.3.0

**Comment by danilkinkin** [comment]
I'm using version 1.3.1, the problem is with `visualTransformation` in file [visualTransformationAsCurrency.kt](https://github.com/danilkinkin/buckwheat/blob/master/app/src/main/java/com/danilkinkin/buckwheat/util/visualTransformationAsCurrency.kt)

**Comment by jedi1150** [comment]
I had the same problem in my own project and it was solved by Compose update

**Comment by danilkinkin** [comment]
I think I fixed this problem in release [2.0.0](https://github.com/danilkinkin/buckwheat/releases/tag/2.0.0). If problem appear again, please reopen
