### ISSUE TITLE
Crash on wallet icon

### ISSUE THREAD

**Issue by ilyaimorozov** [danilkinkin/buckwheat#41]
**Describe the bug**
App crash when I tap whole budget (wallet) icon. Device Poco x3 pro

**To Reproduce**
1. On main screen tap wallet icon
2. App crash

**Screenshots**
![IMG_20230225_125013.jpg](https://user-images.githubusercontent.com/85246919/221350658-324c5a9c-3b34-4057-a75c-7781196881ab.jpg)

**Please complete the following information:**
 - Device: Xiaomi Poco X3 Pro
 - OS: Android 12, MIUI global 13.0.1
 - Version: 1.4

**Comment by danilkinkin** [comment]
Fixed in version [1.4.1](https://github.com/danilkinkin/buckwheat/releases/tag/1.4.1). This problem already fixed uploaded and now i am waiting to approve from Google Play.

Thanks for your issue
