### ISSUE TITLE
Crash on select finish date

### ISSUE THREAD

**Issue by danilkinkin** [danilkinkin/buckwheat#51]
In some languages, the app crashes when opening the due date selector

Noticed in Russian when the start date is earlier than the current one

```
android.content.res.Resources$NotFoundException: Plural resource ID #0x7f0e0001 quantity=-4 item=other
 at android.content.res.ResourcesImpl.getQuantityText(ResourcesImpl.java:331)
 at android.content.res.Resources.getQuantityText(Resources.java:455)
 at android.content.res.Resources.getQuantityString(Resources.java:558)
...
```

**Comment by danilkinkin** [comment]
Fixed in version [1.9.0](https://github.com/danilkinkin/buckwheat/releases/tag/1.9.0)

**Comment by 8549** [comment]
Occurring again in version 3.13.0. The app crashes everytime when tapping on select finish date (I'm trying to setup my first budget, installed the apl yesterday).

Pixel 4a 5G
Android 12
language/locale: it-IT

**Comment by danilkinkin** [comment]
Thanks. Yep, it's bug in it-IT locale. Already fixed it and publish in next release
