### ISSUE TITLE
Instant crash on launch

### ISSUE THREAD

**Issue by TheSunCat** [danilkinkin/buckwheat#53]
**Describe the bug**
Hi! Thank you for maintaining this app. I have been using it for about a week, and a few days ago it started crashing less than a second after loading the UI. I was able to clear the storage to restore functionality, but it has started happening again today.

**To Reproduce**
1. Use the app for some days
2. Observe instant crashing on launch

**Expected behavior**
Ability to use the app.

**Please complete the following information:**
 - Device: Google Pixel 3a
 - OS: LineageOS (Android 13)
 - Version: 1.9.0 (F-Droid)

**Additional context**
I would be happy to provide logs, but I have not found how to access them. Nothing is printed to logcat (I have root on my device) when it crashes.

**Comment by danilkinkin** [comment]
Hello, sorry for long answer. Can you check problem still exist in release [2.0.0](https://github.com/danilkinkin/buckwheat/releases/tag/2.0.0)

**Comment by TheSunCat** [comment]
Apologies for taking so long, but I got back into using it recently and it has not crashed a single time. Thank you again!
