### ISSUE TITLE
language settings don't work on MIUI

### ISSUE THREAD

**Issue by alpha4041** [danilkinkin/buckwheat#54]
When I try to choose a language the Settings app crashes.
I'm using:
- Xiaomi 11 Lite 5G NE
- MIUI 14 xiaomi.eu
- Android 13

I guess the cause it's that MIUI doesn't have Android 13's language settings, a function in the app code to detect MIUI and don't use the Android language settings could be useful to fix this issue.

**Comment by danilkinkin** [comment]
Fixed this problem in release [2.0.0](https://github.com/danilkinkin/buckwheat/releases/tag/2.0.0). If problem appear again, please reopen
