### ISSUE TITLE
Make the tutorial on how to edit spending more explicit

### ISSUE THREAD

**Issue by Disaster2life** [danilkinkin/buckwheat#62]
**Is your feature request related to a problem? Please describe.**
I would like to be able to edit comments I made on earlier expenditures after having made them, I have a terrible memory but also sometimes do not have time  so I would like to be able to for example, go back and recomment some expenses to be more explainatiory than currently.

**Describe the solution you'd like**
probably a small edit icon next to comments which allow you to quickly change previous comments inline right there.

**Describe alternatives you've considered**
I assume a pop up menu could do the job as well but I am unsure if that would fit into the design language of the app.

**Comment by Disaster2life** [comment]
Nevermind, apparently the solution is already implemented, you can slide either ways for options, I think I will keep this open as there probably should be like a tip or something hinting at that? I assume I randomly tried tapping and holding until I figured it out.

**Comment by danilkinkin** [comment]
Improvement in release [v3.0.0](https://github.com/danilkinkin/buckwheat/releases/tag/3.0.0)
