### ISSUE TITLE
Add preset for recurring expenses

### ISSUE THREAD

**Issue by DodoLeDev** [danilkinkin/buckwheat#63]
### Is your feature request related to a problem? Please describe.
Most of my logged expenses are the same recurring ones.
But in the long run, it's repetitive to write the same expense and comment on each one!

### Describe the solution you'd like
I suggest adding a _preset_ feature to the app! Something really simple!

### Describe alternatives you've considered
Until now, I went back to repeating the same operations each time.

### Additional context
I made some mockups of this feature:

<table>
<tr>
 <td><strong>Preset list on the main screen</strong>
 <td><strong><i>"Add preset"</i> button when expense is filled</strong>
 <td><strong>Icon change to notify that the preset has been saved</strong>
<tr>
 <td><img src="https://user-images.githubusercontent.com/59477313/233787060-b4169186-4f0f-4c44-abd0-5ffa038a9cda.png">
 <td><img src="https://user-images.githubusercontent.com/59477313/233787126-2726804e-db49-481b-8544-ae51c6869a28.png">
 <td><img src="https://user-images.githubusercontent.com/59477313/233787127-5a0dfa50-741d-46aa-bbca-e5bf5497d230.png">
</table>

**Comment by danilkinkin** [comment]
Implemented in [v4.0.0](https://github.com/danilkinkin/buckwheat/releases/tag/4.0.0)
