### ISSUE TITLE
Time in CSV exports should include seconds.

### ISSUE THREAD

**Issue by Juliaria08** [danilkinkin/buckwheat#66]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use CSV backups to later when I have time on my computer, create ledger entries of the transactions, and I'd like to document the hours and minutes (and seconds too) of the transactions.

**Solution i'd like**
I'd like for Buckwheat to record the time including seconds of when the transactions where made, and show it in the CSV exports.

**Describe alternatives you've considered**
I've considered manually adding the hour and minute and second in the comment section, but it takes time, and I'd have to manually open the clock app to see seconds.

**Comment by danilkinkin** [comment]
Hi, sorry for long answer.

Can you attach an example csv file? Now, csv is generated with an accuracy of up to a minute.

Or do you also need seconds? Is there a need for this? It is unlikely that spending will be created more than once a minute

**Comment by Juliaria08** [comment]
> Hi, sorry for long answer.
> 
> Can you attach an example csv file? Now, csv is generated with an accuracy of up to a minute.
> 
> Or do you also need seconds? Is there a need for this? It is unlikely that spending will be created more than once a minute

I wanted acuracy with seconds, as I plan to use these exports to import them into ledger.

**Comment by danilkinkin** [comment]
Doesn't your software add seconds automatically when trying to import? For example, zero seconds

**Comment by Juliaria08** [comment]
> Doesn't your software add seconds automatically when trying to import? For example, zero seconds

It would, but I want to store the real second value.

**Comment by danilkinkin** [comment]
But after all, this will not be real time, you at least need to get your phone to write down the spent. It's already 15-50 seconds

**Comment by Juliaria08** [comment]
True, but it's at least more acurate than not having it. If you don't want it, close it. I just liked the idea of having the seconds too.

**Comment by danilkinkin** [comment]
I'll leave this open for now. Maybe someone else will write. While I can't figure out why this is needed, it seems to me that this is redundant information.

In any case, thank you very much for your interest and idea

**Comment by danilkinkin** [comment]
I will close this issue. If someone thinks this is a problem, reopen the issue
