### ISSUE TITLE
Edit day of transaction

### ISSUE THREAD

**Issue by mazenamr** [danilkinkin/buckwheat#69]
**Is your feature request related to a problem? Please describe.**

Case: I want to log my transactions for the day, but it's already past 12 am so it counts as being in the new day.

**Describe the solution you'd like**

Having the ability to set the day of the transaction to one of the past days.

**Describe alternatives you've considered**

Changing my phone's time before adding the transactions and changing it back. Obviously it would be much easier if we could do this right from the app.

**Additional context**

I guess it's not very high priority because in the end it doesn't affect the calculations of the next days. But it matter in record keeping and tracking expenses because without solving this some days will have so little spending and others will have too much.

I like that the app is simple and to the point and this simplicity helps it being more accessible, so asking the user to enter a date for each transaction would go against them. Maybe consider adding this feature when editing a past transaction for example so that it doesn't get in the way, or maybe it should be a small button that doesn't come in the way, like a small clock icon that appears next to the comment button when the user starts typing, with the default value being the current time and date.

**Comment by danilkinkin** [comment]
Implement in release [v.3.11.0](https://github.com/danilkinkin/buckwheat/releases/tag/3.11.0)
