### ISSUE TITLE
zh-rCN translation

### ISSUE THREAD

**Issue by Allium0** [danilkinkin/buckwheat#72]
I've translated your app into Chinese.
[zh-rCN.zip](https://github.com/danilkinkin/buckwheat/files/12368206/zh-rCN.zip)

**Comment by danilkinkin** [comment]
Thanks for your work. I check later.

It would be better if you create the PR through the github tools, if you can't do it, it's not a problem

**Comment by danilkinkin** [comment]
Added in release [v.3.11.0](https://github.com/danilkinkin/buckwheat/releases/tag/3.11.0)
