### ISSUE TITLE
Daily budget more than total with add to current daily

### ISSUE THREAD

**Issue by esdmr** [danilkinkin/buckwheat#85]
**Describe the bug**
If the distribution method is set to add to current daily, The daily budget could grow larger than the total budget. If you then spend the total budget, the message “The budget is over” is shown, but the background still displays the remaining fraction of the daily budget.

**To Reproduce**
1. Setup a three day budget, starting at 1024. Make sure to set the distribution to “add to current daily”.
2. Bring the system date forward by one day. (Or wait yourself. You can also grow the daily budget infinitely large by travelling to the past and back forward multiple times.)
3. Observe that daily budget is more than total budget.

**Expected behavior**
The budget for yesterday plus today should not exceed the total budget. 

**Screenshots**
If applicable add screenshots to help explain your problem.

<img src="https://github.com/danilkinkin/buckwheat/assets/43183709/fef7ed1b-2530-44f6-a525-988cb3ce1105" alt="Screenshot of Buckwheat app, 1024 (100%) left total, 2 days left, 1706.66 for today (which is larger than the total)" width="200px">

<img src="https://github.com/danilkinkin/buckwheat/assets/43183709/74ed1e24-1f13-45f0-82f3-7f03dc43c037" alt="Screenshot of Buckwheat app, 1025 spent, the budget is over, the background shows that only around 40% of the daily budget is spent" width="200px">

**Please complete the following information:**
 - Device: Samsung Galaxy A52s
 - OS: Android 13
 - Version 3.13.0 (F-Droid)

**Additional context**

**Comment by danilkinkin** [comment]
Hi. Thanks, yep I reproduced this bug. I fix in next release asap

**Comment by danilkinkin** [comment]
Fixed in release [v3.16.0](https://github.com/danilkinkin/buckwheat/releases/tag/3.16.0)

**Comment by esdmr** [comment]
@danilkinkin Thank you!
