### ISSUE TITLE
Crash when clicking choose date in the initial setup

### ISSUE THREAD

**Issue by alpha4041** [danilkinkin/buckwheat#86]
**Describe the bug**

**To Reproduce**
1. Install the latest release
2. Set up a budget
3. Click the date selection
4. It crashes

**Expected behavior**
It shouldn't crash

**Please complete the following information:**
 - Device: Xiaomi 11 Lite 5G NE
 - OS: SparkOS 13
 - Version 3.13.0

**Additional context**
https://bin.kv2.dev/~6507daac5de7ed6bfdb94243

**Comment by danilkinkin** [comment]
Hi, I produced this bag. Fixed in next release

**Comment by danilkinkin** [comment]
Fixed in release [v3.16.0](https://github.com/danilkinkin/buckwheat/releases/tag/3.16.0)
