### ISSUE TITLE
UI animation stutters after tapping on "Comment"

### ISSUE THREAD

**Issue by ch3thanhs** [danilkinkin/buckwheat#87]
**Describe the bug**
The UI stutters after tapping on the "Comment".

**To Reproduce**
Steps to reproduce the behavior :
1. Enter some amount spent
2. Tap on "Comment"
3. UI stutters

**Expected behavior**
The comment box should open smoothly.

**Screen recording**

https://github.com/danilkinkin/buckwheat/assets/76928501/c081ee2e-ca48-4a04-b341-f0c2cd330e3a

**Please complete the following information:**
 - OS : Android 13
 - Version : 3.16.0

**Comment by danilkinkin** [comment]
Fixed in [v4.0.0](https://github.com/danilkinkin/buckwheat/releases/tag/4.0.0)

Please reopen if problem still exist

**Comment by ch3thanhs** [comment]
The fix is definitely better but it would be perfect if the text box just expanded in it's place instead of moving.

And probably the amount (₹66 on the screen) should not move?


https://github.com/danilkinkin/buckwheat/assets/76928501/9c8c2935-7d49-4500-9386-dcb07c9c9e8a
