### ISSUE TITLE
Set up publishing in f-droid

### ISSUE THREAD

**Issue by danilkinkin** [danilkinkin/buckwheat#9]
Suggestions links:
- https://dev.to/sanandmv7/how-to-publish-your-apps-on-f-droid-2epn
- https://f-droid.org/docs/FAQ_-_App_Developers/

**Comment by IzzySoft** [comment]
Question at this place: your privacy policy states you don't collect *personal* information. Yet the app uses Sentry, and I don't find it mentioned. Not saying you collect *personal* details via Sentry, but:

* is Sentry configured to be opt-in – or does it "call home" by default?
* what is the Sentry end-point (self-hosted? sentry.io? other?)
* what details are collected?

These details are missing in the privacy policy. Could you please clarify (and include the details there)? Thanks in advance!

That said, F-Droid will ask for [fastlane structures](https://gitlab.com/-/snippets/1895688) to be established in your repo here. I gladly help out with that: I've just added your app to my repo, where it will [show up](https://apt.izzysoft.de/fdroid/index/apk/com.danilkinkin.buckwheat) in about 2 hours from now. For that I've created those structures locally and can offer them via PR if you want them, just let me know.

And finally: best greetings to Erewan, best known for its famous "radio stanzija" :smile:

**Comment by Juliaria08** [comment]
Sentry seems to have been removed, which is one less hurlde I think 😄

**Comment by danilkinkin** [comment]
@IzzySoft, I think I'm ready for it now. 

What do I need to publish? Should I post via PR or can you do it another way? If this is not difficult for you, I would delegate this process to you

**Comment by IzzySoft** [comment]
Oh, it's not difficult **usually™** (can get tricky in the process, though – but sometimes it's as easy as 1-2-3). See e.g. [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid) for a short outline. Or for some more details on the RFP part: [the process of integrating an app with F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-2) in a blog post of mine. We'd prefer you start the process (as that clearly states you support it), and will guide you through once the RFP/MR are created.

**Comment by danilkinkin** [comment]
Ohh, it's so confused for me. I chose RFP method, it's longer, but I think easier. Can you check please [my issue](https://gitlab.com/fdroid/rfp/-/issues/2552)?

**Comment by danilkinkin** [comment]
@IzzySoft, do you know how I can restart F-Droid bot check? I fixed issues, but don't understand how I can restart checks

**Comment by IzzySoft** [comment]
You can't, only the F-Droid team can (needs elevatedd privileges to handle labels). I've just triggered a rescan (by removing the fdroidbot label).

**Comment by danilkinkin** [comment]
@IzzySoft, sorry again. Can you remove `fdroid-bot` label again? Yep, I'm slooow

**Comment by IzzySoft** [comment]
Sorry, but I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447).

**Comment by danilkinkin** [comment]
Hmm, skiped this conflict. Sounds sad. Can you recomend other good alternative store or any suggestion. I want to have alternative of Google Play

**Comment by ClockGen** [comment]
Hello, I can help you get your app published on F-Droid. I'm gonna try to set up metadata for it and see if it builds on f-droid buildserver and if any problems arise.

**Comment by danilkinkin** [comment]
@ClockGen, I already prepared metadata. Now, tried to fix conflicts in [this issue](https://gitlab.com/fdroid/rfp/-/issues/2552). If you can help there with questions, it's great

**Comment by ClockGen** [comment]
Don't worry about the bot, it's just for scans, actual app submissions are still processed by maintainers or contributors and added manually in fdroiddata repository: https://gitlab.com/fdroid/fdroiddata/-/merge_requests. Also by metadata I mean not fastlane metadata, but F-Droid's metadata for apps, it contains build recipe, various app information (like that translation link mentioned above). It's needed to test if the app builds and complies with inclusion criteria anyway and I have a buildserver, so I'll write one for you. If there's any problems I'll let you know.

**Comment by danilkinkin** [comment]
Oh, thanks. Actually, I think publish process in F-Droid looks non-friendly( And I would be very grateful if you could help me with this. Huge thanks

**Comment by danilkinkin** [comment]
Buckwheat now in F-Droid too 🎉
