### ISSUE TITLE
Some date is missing in date picker

### ISSUE THREAD

**Issue by Icarus-Xu** [danilkinkin/buckwheat#95]
**Describe the bug**
The last day of some month displayed out of screen

**To Reproduce**
1. Go to date picker and check Dec 2023, Mar 2024, June 2024, August 2025 etc.

**Expected behavior**
It seems that if the end of a month is Sunday, it will not start a new line, plz check following screenshot

**Screenshots**
![dec2023](https://github.com/danilkinkin/buckwheat/assets/11155311/16ba7ce7-75ab-45e5-8561-35d3b8bd8e23)
![mar2024](https://github.com/danilkinkin/buckwheat/assets/11155311/3f668bf1-7810-4246-89a4-aeb6744e53d5)
![jun2024](https://github.com/danilkinkin/buckwheat/assets/11155311/8b74eeed-2bc3-454f-b50f-0a4d08448a5f)
![aug2025](https://github.com/danilkinkin/buckwheat/assets/11155311/d5a520af-f976-4dd4-9b89-5135f5cb0bc9)

**Please complete the following information:**
 - Device: Poco F2 Pro
 - OS: LineageOS @ Android13
 - Version: 3.16.0

**Comment by danilkinkin** [comment]
Fixed in [v4.0.0](https://github.com/danilkinkin/buckwheat/releases/tag/4.0.0)

Please reopen if problem still exist

**Comment by Icarus-Xu** [comment]
Confirm fixed, thank you.
